version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped
